---
- name: deploy a terraform project
  hosts: webserver
  tasks: 
    - name: install httpd
      yum: 
        name: httpd
        state: latest
    - name: start httpd service
      service: 
        name: httpd
        state: started
    - name: deploy application
      copy:
        content: "<html><body>Welcome to devops</body></html>"
        dest: /var/www/html/index.html
      
      